name: Deploy website on push

on:
  push:
    branches:
     - dev
 jobs:
  web-deploy:
    name: Deploy
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest codes
    
    uses: actions/checkout@v2
    
    - name: Sync files
      uses: Samkirkland/FTP-Deploy-Action@4.1.0
      with: 
        server: ftp.lykluk.com
        username: ${{ secrets.FTP_USER }}
        passpword: ${{ secrets.FTP_PASS }}
        server-dir: /
